name: Android Release

on: workflow_dispatch

permissions:
  contents: write

env:
  PROJECT_NAME: BFEXEOPT

jobs:
  build:
    name: ${{ matrix.name }}

    strategy:
      matrix:
        include:
          - name: Android x64
            os: macos-15
            buildArgs: "android -final -ONLY_ARM64"
            artifactName: Android x64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"

          - name: Android x32
            os: macos-15
            buildArgs: "android -final -ONLY_ARMV7"
            artifactName: Android x32
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Android x64
        uses: actions/download-artifact@v4
        with:
          name: Android x64
          path: /home/runner/android-x64

      - name: Rename Android x64
        run: |
          mv /home/runner/android-x64/*.apk \
             /home/runner/${{ env.PROJECT_NAME }}-Android-x64.apk

      - name: Download Android x32
        uses: actions/download-artifact@v4
        with:
          name: Android x32
          path: /home/runner/android-x32

      - name: Rename Android x32
        run: |
          mv /home/runner/android-x32/*.apk \
             /home/runner/${{ env.PROJECT_NAME }}-Android-x32.apk

      - name: Publish Android Release
        uses: softprops/action-gh-release@v2
        with:
          name: "BFEXEOPT Android"
          tag_name: "1.0.4"
          make_latest: true
          files: |
            /home/runner/${{ env.PROJECT_NAME }}-Android-x64.apk
            /home/runner/${{ env.PROJECT_NAME }}-Android-x32.apk
